#! /bin/bash

SWWW_TRANSITION=random
export stills="$1"

wallpaper () {
    for monitor in "${monitors[@]}"; do swww img --transition-type random --outputs $monitor "$(randstill)"; done
  }

#Function to select a random file from $stills directory
randstill() {
    find "$stills" -maxdepth 1 -type f | shuf -n 1
}

#Switches wallpaper based on charging status
wptoggle () {
    #Identify active monitors
    monitors=($(hyprctl monitors | awk '{if ($1 ~ "Monitor") print $2}'))
    hyprctl keyword decoration:blur_new_optimizations 1

    wallpaper
    while pgrep swww; do
      sleep 300
      wallpaper
    done
  }

#perform cleanup and exit
wall=$(find ~/.config/hypr/themes/cyber/wallpaper/ -type f -name "*.jpg" -o -name "*.png" -o -name "*.gif" | shuf -n 1)

swww kill
swww init

# Picks background wallpaper
swww img $wall


# generate color scheme
wal -c
wal -i $wall


# Enable this (by removing the # next to pywalfox update) if you use firefox AND downloaded the pywalfox extension and installed repository.
 pywalfox update


# Deletes the sww cache
rm -rf $HOME/.cache/swww
